base:
  api:
    url: http://22.22.22.22
    credential:
      username: foo
      password: bar
  sandbox: ../windows-container/Debug/winc.exe
  runtimeDirectory: ../runtime
  compile:
    timeout: 20000
    source: '{runtimeDir}/compile/{submission.user.userName}/{submission._id}.c'
    target: '{runtimeDir}/compile/{submission.user.userName}/{submission._id}.exe'
    clean:
      - '{compileConfig.source}'
      - '{compileConfig.target}'
    command: gcc
    args: -O2 -s -Wall -std=c11 -o "{compileConfig.target}" "{compileConfig.source}" -lm -Wl,--stack=134217728
    sandboxArgs: --use-logon
  match:
    s1bin: '{runtimeDir}/match/{task.mdocid}/{task.rid}/{task.s1docid}.exe'
    s2bin: '{runtimeDir}/match/{task.mdocid}/{task.rid}/{task.s2docid}.exe'
    opening: '{runtimeDir}/match/{task.mdocid}/{task.rid}/opening.json'
    config: '{runtimeDir}/match/{task.mdocid}/{task.rid}/config.json'
    summary: '{runtimeDir}/match/{task.mdocid}/{task.rid}/summary.json'
    clean:
      - '{runtimeDir}/match/{task.mdocid}/{task.rid}/**'
    command: node
    args: ../fun-judge/.dist/bootstrap.js --config "{matchConfig.config}"
  mq:
    vhosts:
      /:
        connection:
          hostname: 22.22.22.22
          user: guest
          password: guest
        queues:
          - gomoku_compile
          - gomoku_judge
        subscriptions:
          compile:
            queue: gomoku_compile
            prefetch: 1
          judge:
            queue: gomoku_judge
            prefetch: 4  # set to number of CPUs / 2 - 1
