base:
  api:
    url: http://22.22.22.22
    credential:
      username: foo
      password: bar
  # relative to current dir
  sandbox: ../windows-container/Release/winc.exe
  # relative to current dir
  runtimeDirectory: ../runtime
  compile:
    timeout: 20000
    source: foo.c
    target: foo.exe
    command: gcc
    args: -O2 -s -Wall -std=c11 -o foo.exe foo.c -lm -Wl,--stack=134217728
    sandboxArgs: --use-logon
  match:
    s1bin: ./challenger.exe
    s2bin: ./opponent.exe
    opening: opening.json
    config: config.json
    summary: summary.json
    command: node
    # relative to the working directory
    args: ../../../fun-judge/.dist/bootstrap.js --config config.json
  mq:
    vhosts:
      /:
        connection:
          hostname: 22.22.22.22
          user: guest
          password: guest
        queues:
          - gomoku_compile
          - gomoku_judge
        subscriptions:
          compile:
            queue: gomoku_compile
            prefetch: 1  # don't modify it! only one submission at a time!
          judge:
            queue: gomoku_judge
            prefetch: 1  # set to number of floor((CPUs - 1) / 2)
