base:
  api:
    url: http://22.22.22.22
    credential:
      username: foo
      password: bar
  sandbox: ../windows-container/Debug/winc.exe
  runtimeDirectory: ../runtime
  compile:
    timeout: 20000
    source: compile/{submission.user.userName}/{submission._id}.c
    target: compile/{submission.user.userName}/{submission._id}.exe
    command: gcc -O2 -s -Wall -std=c11 -o "{compileConfig.target}" "{compileConfig.source}" -lm -Wl,--stack=134217728
    sandboxArgv: --use-logon
  match:
    s1bin: match/{task.mdocid}/{task.rid}/{task.s1docid}.exe
    s2bin: match/{task.mdocid}/{task.rid}/{task.s2docid}.exe
    map: match/{task.mdocid}/{task.rid}/map.json
    config: match/{task.mdocid}/{task.rid}/config.json
    command: node ../../fun-judge/.dist/bootstrap.js --config {matchConfig.config}
  mq:
    vhosts:
      /:
        connection:
          hostname: 22.22.22.22
          user: guest
          password: guest
        queues:
          - gomoku_compile
          - gomoku_judge
        subscriptions:
          compile:
            queue: gomoku_compile
            prefetch: 1
          judge:
            queue: gomoku_judge
            prefetch: 4  # set to number of CPUs - 1
